language: node_js
sudo: false
node_js:
- '7'
branches:
  only:
  - master
  - dev
script:
- npm test
- npm run lint
after_script:
- npm run coveralls
deploy:
  provider: npm
  email: gmer@hcuge.ch
  skip_cleanup: true
  api_key:
    secure: yqH4hLlDohGqzxMXtCwBXbn5oQ3yMEoz2q4Jpl2spasNpWs3mxCGxw9Rg6ulWj7wrHIpKIffGm23vNy1c3UUc/C+Wag8Z1sVzAi4Eu5DAwFasnLG0krOnP35FKcF941AExAXj0bhhKTD2j2TslMSADyz8QzP2YZIDe+6wwh1xHmVGxX9RCTY4AjTuhEj2Qoae54uMn2iyB76S/mX1HjvTX7IqEFMat7xvaClz7KzuRtqGFgl89bEXR3zWBGFm16sP8XRFWxdgt6dhp1ZCPAjPfZOH28f0AYJn0wjnnysOd/cUW4RiuG4huXpvl6NK+/fpJtW6E6IL7F/q5TsKW5E77/zmGcRY2Hhrw5nSbWEgkp6jf67kDACSaUCF2NUVXva5IlCQ31XFkEnOxOmV8lDr/Q8f0O6cz/4Be8URRNlCqliVMoDpexgHwd3BtyvqdU+9WZ9NM1pCWHCU3HTUNnLTT/7eHwsBvdlnQRLCugHOhARID4kr62efM0phazwK06kQeE5UaYgAeBTv59dXMoUpuPzyfkbG+7s89jPSb/PA1VTi8IQX3OTSfbyACdc6Sy2hVbyCJX+5LYL+ARQlmOEJRE77iyFfQYjgYQ4+q2EwzygegwStT/NgvJHd4yotU9y8k3XaBfx4G5M/gi5V8BN8a1yMGHbrCVX8i4a72BX9xQ=
  on:
    repo: DSI-HUG/generate-changelog
    branch: master