language: node_js
sudo: false
node_js:
- '6'
- '7'
branches:
  only:
  - master
  - dev
script:
- npm test
- npm run lint
after_script:
- npm run coveralls
deploy:
  provider: npm
  email: gmer@hcuge.ch
  skip_cleanup: true
  api_key:
    secure: MfnzVfTBhHcGjr6/RPW+ipxhNBmVlLZsoAZ8eyJ8AJ+o3VV/6CHec2znb2E78MsQAMU2yK/TLYzPxe2dSNF90ifYonsr4cVypoxKCabxSf1nN3qzwUKbAYDGjb6Md7qM67dDEq6umDoWS+hFHCCYUnT2kK3WA6Zvrx6o4Vzy/BwRftvLt+a9Lfk8BfjDqwTM/dOtVeO86G4N5iTZ+4njISjB73lZJukN6ccD9v+Wr7vxL8U4CLbk+MamYbnQDJEbiPGAT+fksijCH81IevWOVQKneBasegneKZWdFbPEaelORTygqu2ChIBs6B6DU1lRcKabpIZ3Jpnz8W0PiIjDHGEssEDKcTU89xQugZ27UyOu0rW8XH1qnot2UCBkN3PQMNGg4DEaNYe8NP2VGrppa0hMAlXYXNelhOFp80GSMgNbA2WUmTjplTqakYV3JNXJ2EI8OZ1jhOdUT/p+9nHNADU5GGNMXQpiGtFsvwVtXlzwqCtzDeDVTkJLtrghfVPmQNHVjE9VUAS8jvlx0cMWV+uKNQVn+mBOfeSNbx/Y+OYrVfgM0PnQ+i2GbIfzAqkf4xTjY3n8v5yjWniKnw+7j5IyZN94Wmr1Gy8vPZOdwUx4gHhCc3e3eWmZV1B7yEua7Jy3ZPLPuc8MlKP1g/Chsc0gLLOrVpdPaEEU5H5JFNs=
  on:
    repo: DSI-HUG/generate-changelog
    branch: master